# Generated by Django 4.0.4 on 2022-06-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_despacho_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='COMPRADO'),
        ),
    ]
