# Generated by Django 4.0.4 on 2022-06-25 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_despacho_estado_alter_estado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='estado',
            field=models.ForeignKey(blank=True, choices=[[0, 'Comprado']], null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estado'),
        ),
    ]
